backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:

  - name: users
    label: Users
    format: yml
    extension: yml
    folder: data/users/
    create: true
    slug: '{{title}}'
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Image, name: image, widget: image, required: true}     
  

  - name: stay
    label: stay
    files:
      - file: data/stays/image.yml
        label: Images
        name: images
        fields:
          - label: Slide Image
            name: images
            widget: list
            fields:
              - {label: Image, name: image, widget: image}
      - file: data/stays/maped.yml
        label: Map
        name: map
        fields:
          - {label: Map, name: mapadd, widget: map}
      - file: data/stays/accordion.yml
        label: Accordion
        name: accordion
        fields:
          - label: Accordion
            name: accordion
            widget: list
            fields:
              - {label: Icon, name: icon, widget: image}
              - {label: Id, name: id, widget: number}
              - {label: Title, name: title, widget: text}
              - {label: Content, name: content, widget: string}
              


  - name: events
    label: Events
    files:
      - file: "data/events/events.yml"
        label: Events
        name: events
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Story
            name: story
            widget: markdown